import { Inter } from "next/font/google";
import "./globals.css";
import TransitionProvider from "@/_components/TransitionProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "AKM Portfolio App",
  description: "Generated by AKM Dev",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TransitionProvider>{children}</TransitionProvider>
      </body>
    </html>
  );
}
